In [6]:
import pandas as pd

In [15]:
# artist = pd.read_excel('artists_details with id.xlsx')
# artist.head()

,names,members,birth_name,birth_place,birth_date,gender,category,spotify track artist audio.artist_name,spotify track artist audio.artist_id
0,Taylor Swift,NaN,Taylor Alison Swift,"[[West Reading, Pennsylvania]], U.S.",{{Birth date and age|1989|12|13}},female,American_female_country_singers,Taylor Swift,06HL4z0CvFAxyc27GXpf02
1,Thomas Rhett,NaN,Thomas Rhett Akins Jr.,"[[Nashville, Tennessee]], U.S.",{{birth date and age|1990|03|30}},male,American_male_singers,Thomas Rhett,6x2LnllRG5uGarZMsD4iO8
2,Bruno Mars,NaN,Peter Gene Hernandez,"[[Honolulu|Honolulu, Hawaii]], U.S.",{{birth date and age|1985|10|08}},male,American_male_singer-songwriters,Bruno Mars,0du5cEVh5yTK9QJze8zA0C
3,Ed Sheeran,NaN,Edward Christopher Sheeran,"[[Halifax, West Yorkshire]], England",{{Birth date and age|df|=|y|1991|2|17}},male,English_male_singers,Ed Sheeran,6eUKZXaKkcviH0Ku9w2n3V
4,Bill Conti,NaN,William Conti,"[[Providence, Rhode Island]], U.S.",{{Birth date and age|1942|4|13}},male,NaN,Bill Conti,272ygo5fv9cYsiCLcV0HV2

In [56]:
artist.isnull().sum()

names                                       79
members                                   1313
birth_name                                1223
birth_place                                101
birth_date                                1061
gender                                    1327
category                                  1514
spotify track artist audio.artist_name     321
spotify track artist audio.artist_id       321
dtype: int64

In [53]:
artist[artist['gender'].isnull()].head(20)

,names,members,birth_name,birth_place,birth_date,gender,category,spotify track artist audio.artist_name,spotify track artist audio.artist_id
365,Silverchair,NaN,NaN,"[[Newcastle, New South Wales]], Australia",NaN,NaN,NaN,Silverchair,4iudEcmuPlYNdbP3e1bdn1
366,Semisonic,* [[John Munson]]\n* [[Jacob Slichter]]\n* [[D...,NaN,"[[Minneapolis|Minneapolis, Minnesota]], U.S.",NaN,NaN,NaN,Semisonic,1TqQi97nqeiuOJrIFv5Sw0
367,Soundgarden,NaN,NaN,"[[Seattle|Seattle, Washington]], U.S.",NaN,NaN,NaN,Soundgarden,5xUf6j4upBrXZPg6AI4MRK
368,The Offspring,* [[Dexter Holland]]\n* [[Noodles (musician)|N...,NaN,"[[Garden Grove, California]], U.S.",NaN,NaN,NaN,The Offspring,5LfGQac0EIXyAN8aUwmNAQ
369,Korn,* [[Jonathan Davis]]\n* [[James Shaffer]]\n* [...,NaN,"[[Bakersfield, California]], U.S.",NaN,NaN,NaN,Korn,3RNrq3jvMZxD9ZyoOZbQOD
370,Stone Temple Pilots,* [[Dean DeLeo]]\n* [[Robert DeLeo]]\n* [[Eric...,NaN,"[[San Diego, California]], U.S.",NaN,NaN,NaN,Stone Temple Pilots,2UazAtjfzqBF0Nho2awK4z
371,Blind Melon,* [[Rogers Stevens]]\n* Christopher Thorn\n* G...,NaN,"[[Los Angeles]], [[California]], U.S.",NaN,NaN,NaN,Blind Melon,5sD1ZLf2dGQ9gQ3YJl1eAd
372,The Smashing Pumpkins,* [[Billy Corgan]]\n* [[James Iha]]\n* [[Jimmy...,NaN,"[[Chicago]], [[Illinois]], U.S.",NaN,NaN,NaN,The Smashing Pumpkins,40Yq4vzPs9VNUrIBG5Jr2i
374,Wheatus,Brendan B. Brown<br>Matthew Milligan<br>Brando...,NaN,"[[Northport, New York]], United States",NaN,NaN,NaN,Wheatus,4mYFgEjpQT4IKOrjOUKyXu
375,Nine Days,John Hampson<br />Brian Desveaux<br />Jeremy D...,NaN,"[[Long Island, New York|Long Island]], [[New Y...",NaN,NaN,NaN,Nine Days,306JHpIRGVaQd6OltnOzUO
376,Everclear,NaN,NaN,[[United States]],NaN,NaN,NaN,Everclear,694QW15WkebjcrWgQHzRYF
377,Ben Folds Five,NaN,NaN,"[[Chapel Hill, North Carolina]], U.S.",NaN,NaN,NaN,Ben Folds Five,44gRHbEm4Uqa0ykW0rDTNk
379,The Boo Radleys,Tim Brown<br/>Simon “Sice” Rowbottom<br/>Rob C...,NaN,"[[Wallasey]], England",NaN,NaN,NaN,The Boo Radleys,6UYwzZChuolxsylHcZcBBP
380,Dog's Eye View,NaN,NaN,"Los Angeles, California",NaN,NaN,NaN,Dog's Eye View,0ymKv4fh2eBhPT9HLTu8yH
381,Seven Mary Three,NaN,NaN,"[[Williamsburg, Virginia]], [[United States]]",NaN,NaN,NaN,Seven Mary Three,2zsLaQhHFdQPdFXqG1nRmM
382,Candlebox,[[Kevin Martin (American musician)|Kevin Marti...,NaN,"[[Seattle]], Washington",NaN,NaN,NaN,Candlebox,3R6c2tWDBeYB1GncjLMn9n
383,ZZ Top,*[[Billy Gibbons]]\n* [[Frank Beard (musician)...,NaN,"[[Houston|Houston, Texas]], U.S.",NaN,NaN,NaN,ZZ Top,2AM4ilv6UzW0uMRuqKtDgN
384,Metallica,* [[James Hetfield]]\n* [[Lars Ulrich]]\n* [[K...,NaN,"[[Los Angeles]], [[California]], U.S.",NaN,NaN,NaN,Metallica,2ye2Wgw4gimLv2eAKyk1NB
386,Damn Yankees,NaN,NaN,NaN,NaN,NaN,NaN,Damn Yankees,7ihLzUpuNecU5VBkvOUDNq
387,INXS,NaN,NaN,"[[Sydney, New South Wales]], Australia",NaN,NaN,NaN,INXS,1eClJfHLoDI4rZe5HxzBFv

In [52]:
artist.loc[[], 'gender'] = 'male'
artist.loc[[], 'gender'] = 'female'
artist.loc[[], 'gender'] = 'male, female'

# not artists or duplicates
# artist.drop([98, 196, 197, 238, 253, 2093, 2097, 2103], inplace=True)
# artist.drop([299, 307], inplace=True)


# artist.loc[[336, 338, 339, 342, 351, 355, 358, 359, 360, 361, 362, 363 ], 'gender'] = 'male'
# artist.loc[[345, 357], 'gender'] = 'female'
# artist.loc[[346, 347, 349, 352, 353, 356,  ], 'gender'] = 'male, female'
# artist.loc[[305, 309, 310, 317, 318, 320, 322, 329, 330, 332, 333, 334, 335], 'gender'] = 'male'
# artist.loc[[294, 308, 319, 323  ], 'gender'] = 'female'
# artist.loc[[274, 286, 312], 'gender'] = 'male, female'
# artist.loc[300, ['members', 'birth_place', 'gender']] = ['Rudolf Schenker', 'Klaus Meine', 'Matthias Jabs', 
#                                                         'Paweł Mąciwoda', 'Mikkey Dee'], 'Germany', 'male'
# artist.loc[[273, 276, 281, 282, 283, 285, 287, 290, 291, 295, 297, 298], 'gender'] = 'male'
# artist.loc[294, 'gender'] = 'female'
# artist.loc[[274, 286 ], 'gender'] = 'male, female'
# artist.loc[[248, 249, 250, 251, 252, 254, 257, 260, 262, 263, 264, 265, 267, 268, 271], 'gender'] = 'male'
# artist.loc[[222, 224, 225, 226, 227, 228, 229, 230, 233, 234, 235, 236, 240, 242, 243, 245], 'gender'] = 'male'
# artist.loc[[178, 179,181, 183, 189, 191, 192, 193, 194, 195, 208, 211, 216, 217, 219, 221], 'gender'] = 'male'
# artist.loc[203, 'gender'] = 'male, female'
# artist.loc[[141, 145, 146, 147, 155, 158, 160, 161, 162, 164, 170, 177 ], 'gender'] = 'male'
# artist.loc[[139, 143, 144, 159, 163, 168,   ], 'gender'] = 'female'
# artist.loc[175, 'gender'] = 'male, female'
# artist.loc[[82, 88, 89, 90, 96, 108, 112, 113, 120, 129, 134, 135, 136, 137, 138], 'gender'] = 'male'
# artist.loc[[87, 92, 132], 'gender'] = 'female'
# artist.loc[[122, 125], 'gender'] = 'male, female'
# artist.loc[[82, 83, 84, 85, 86,  ], 'gender'] = 'male'
# artist.loc[[2094,2095], 'gender'] = 'female'
# artist.loc[[39, 43, 44, 45, 46, 47, 49, 52, 54, 62], 'gender'] = 'male'
# artist.loc[[64, 65, 66, 69, 70, 2100, 2101, 2102, 2104 ], 'gender'] = 'male'
# artist.loc[[74, 79, 80 ], 'gender'] = 'male'
# artist.loc[[2096, 2098, 2099 ], 'gender'] = 'female'
# artist.loc[[71, 73 ], 'gender'] = 'male, female'

In [59]:
artist.to_csv('artists_details_with_id_gender.csv', index=False)

In [ ]:
# country = coco.convert(element, to='name_short')
# import country_converter as coco